import type { Metadata } from "next";
import { Quantico } from "next/font/google";
import "./globals.css";
import { FiltersProvider } from "@/context/filters";

const quantico = Quantico({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quantico.className} overflow-hidden`}>
        <FiltersProvider>
          {children}
        </FiltersProvider>
      </body>
    </html >
  );
}
